export const GET_TRACKS = 'GET_TRACKS';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_ERROR = 'GET_TRACKS_ERROR';

export const ADD_TRACK = 'ADD_TRACK';
export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS';
export const ADD_TRACK_ERROR = 'ADD_TRACK_ERROR';
